apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-mitechcondemo
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: 'mitechcondemo:qa'
  labels:
    stack: mitechcondemo
    stage: qa
spec:
  project: default
  destination:
    name: dev
    namespace: m3test
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  sources:
  - repoURL: example.repo.com/helm-charts
    targetRevision: 0.2.2
    chart: mitechcondemo
    helm:
      releaseName: 'qa-mitechcondemo'
      valuesObject:
        config:
          message: "This is a helm chart installed by appset for qa"
        deployment:
          image:
            repo: example.repo.com
            name: m3test/mitechcondemo
            tag: 0.2.4
          envs:
            RUN_ENV: 'qa'
            TXT_COLOR: 'orange'
        ingress:
          host: 'qa-mitechcondemo.example.com'
