apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-mitechcondemo
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: 'mitechcondemo:staging'
  labels:
    stack: mitechcondemo
    stage: staging
spec:
  project: default
  destination:
    name: dev
    namespace: m3test
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  sources:
  - repoURL: example.repo.com/helm-charts
    targetRevision: 0.1.0
    chart: mitechcondemo
    helm:
      releaseName: 'staging-mitechcondemo'
      valuesObject:
        config:
          message: "This is a helm chart installed by appset for staging"
        deployment:
          image:
            repo: example.repo.com
            name: m3test/mitechcondemo
            tag: 0.1.1
          envs:
            RUN_ENV: 'staging'
            TXT_COLOR: 'blue'
        ingress:
          host: 'staging-mitechcondemo.example.com'
