{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mitechcondemo.fullname" . }}-message
  labels:
  {{- include "mitechcondemo.labels" . | nindent 4 }}
data:
  message: {{ .Values.config.message | toYaml | indent 1 }}

  title: "Hello MiTechCon 2025!"

{{- end -}}
