apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "mitechcondemo.labels" . | nindent 4 }}
  name: {{ include "mitechcondemo.fullname" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ include "mitechcondemo.fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "mitechcondemo.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.deployment.image.repo }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag | default
          .Chart.AppVersion }}
        imagePullPolicy: Always
        name: mitechcondemo
        ports:
        - containerPort: 8501
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
            cpu: 800m
          requests:
            cpu: 300m
            memory: 1Gi
        env:
        {{- if .Values.deployment.envs }}
        {{- range $key, $value := .Values.deployment.envs }}
        - name: {{ $key }}
          value: {{ quote $value }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: message
          mountPath: /application/title.txt
          subPath: title
        - name: message
          mountPath: /application/message.txt
          subPath: message
        - name: scratch
          mountPath: /application/temp
      restartPolicy: Always
      volumes:
      - name: message
        configMap:
          name: {{ include "mitechcondemo.fullname" . }}-message
      - name: scratch
        emptyDir: {}
