apiVersion: v1
kind: Service
metadata:
  name: {{ include "mitechcondemo.fullname" . }}-service
spec:
  ports:
    - name: mitechcondemo
      port: 8501
      targetPort: 8501
  selector:
    app: {{ include "mitechcondemo.fullname" . }}
